# Generated by Django 4.1.5 on 2023-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolbeansapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='addressee',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
